version: '3.9'
services:
  front:
    build:
      context: .
      dockerfile: Dockerfile
    # コンテナ名指定はなくて良い
    # container_name: reactapp
    command: sh -c "cd front && npm start"
    environment:
      - NODE_ENV=development
    ports:
      # 5173だと動かない、多分React.js側の設定項目を変える必要がある
      # - 5173:5173
      - 3000:3000
    stdin_open: true
    tty: true
    volumes:
      # このvolumes指定しないとホスト側にファイル変更などが反映されない
      - ./:/usr/src/app:cached
      # FIXME: node_moduleの中身がない問題を解決できていない
      # [【Docker】node_module の volume 設定に関して（Rails / ruby,node環境） - 7839](https://serip39.hatenablog.com/entry/2022/08/10/120000)
      - node_modules:/usr/src/app/node_modules

volumes:
  node_modules:
    driver_opts:
      type: none
      device: ${PWD}/front/node_modules
      o: bind
