version: '3.9'
services:
  front:
    build:
      context: .
      dockerfile: Dockerfile
    # コンテナ名指定はなくて良い
    # container_name: reactapp
    command: sh -c "cd front && npm start"
    environment:
      - NODE_ENV=development
    ports:
      # 5173だと動かない、多分React.js側の設定項目を変える必要がある
      # - 5173:5173
      - 3000:3000
    stdin_open: true
    tty: true
    volumes:
      - ./front:/usr/src/app
      - node-modules:/frontapp/node_modules:cached

volumes:
  node-modules:
